services:
    miguel_bacalhau.service:
        class: miguel\BacalhauBundle\Api\Service
        arguments:
          entityManager: "@doctrine.orm.entity_manager"

    miguel_bacalhau.user:
        class: miguel\BacalhauBundle\Api\Service\User
        parent: miguel_bacalhau.service
